// Generated by ts-to-zod
import { setIdSchema, refSchema } from "@/common/zod/base";
import { socialNodeSchema } from "@/common/zod/social";
import { z } from "zod";

export const genreSchema = setIdSchema;

export const universeSchema = socialNodeSchema.extend({
  concept: z.string(),
  owner: z.string().optional(),
  genres: z.tuple([genreSchema]).optional(),
});

export const characterSchema = socialNodeSchema.extend({
  about: z.string(),
  universe: refSchema.optional(),
});

export const storySchema = socialNodeSchema.extend({
  synopsis: z.string(),
  universe: refSchema.optional(),
  genre: genreSchema.optional(),
});

export const pageSchema = socialNodeSchema.extend({
  content: z.string(),
  universe: refSchema.optional(),
  story: refSchema.optional(),
  pgNum: z.number().optional(),
});

export const authorSchema = refSchema;
