// Generated by ts-to-zod
import { z } from "zod";
import { type Navigate, CardType } from "./viewTypes";

export const cardTypeSchema = z.nativeEnum(CardType);

export const navigateSchema: z.ZodSchema<Navigate> = z.lazy(() =>
  z.object({
    screen: z.string(),
    params: navigateSchema.optional(),
    push: z.boolean().optional(),
  }),
);

export const actionSchema = z.union([
  navigateSchema,
  z.object({
    name: z.string(),
  }),
]);

export const actionsSchema = z.object({
  press: actionSchema.optional(),
  longPress: actionSchema.optional(),
  doubleTap: actionSchema.optional(),
  submit: actionSchema.optional(),
  more: actionSchema.optional(),
  like: actionSchema.optional(),
  share: actionSchema.optional(),
  comment: actionSchema.optional(),
  button: actionSchema.optional(),
});

export const cardDataSchema = z.object({
  PK: z.string().optional(),
  SK: z.string().optional(),
  type: z.string().optional(),
  id: z.string().optional(),
  key: z.string().optional(),
  text: z.string().optional(),
  coverImage: z.string().optional(),
  synopsis: z.string().optional(),
  title: z.string().optional(),
  owner: z.string().optional(),
  titleColor: z.string().optional(),
  authored: z.boolean().optional(),
  era: z.string().optional(),
  world: z.string().optional(),
  genres: z.tuple([z.string()]).optional(),
  cardType: cardTypeSchema.optional(),
  style: z.any().optional(),
  actions: actionsSchema.optional(),
  loved: z.boolean().optional(),
  followed: z.boolean().optional(),
});

export const sectionDataSchema = z.object({
  source: z.string().optional(),
  data: z.array(cardDataSchema),
  fieldMappings: z.record(z.string()).optional(),
  index: z.number().optional(),
  title: z.string().optional(),
  horizontal: z
    .object({
      snap: z.any().optional(),
    })
    .optional(),
  cardType: cardTypeSchema.optional(),
  noAuthoredHint: z.boolean().optional(),
  actions: actionsSchema.optional(),
  style: z.any().optional(),
});

export const compositeScrollerDataSchema = z.object({
  sections: z.array(sectionDataSchema),
  startScrollPosition: z.number().optional(),
});
