// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl2tfbtvpB_H9_W8lJqkQR6gdTPck1tk4',
    appId: '1:421526355060:web:b4f891461f08df36d5e521',
    messagingSenderId: '421526355060',
    projectId: 'flutterfast-92c25',
    authDomain: 'flutterfast-92c25.firebaseapp.com',
    storageBucket: 'flutterfast-92c25.appspot.com',
    measurementId: 'G-YM48JE94WT',
  );

  static const String webClientId =
      '421526355060-drq1bh64fdhqngdm6tf068cr1pfeat8u.apps.googleusercontent.com';

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArFd_VJGIQLqJ16dg1GzVsG90r_E4L690',
    appId: '1:421526355060:android:0bb7b8bdebc7f5ccd5e521',
    messagingSenderId: '421526355060',
    projectId: 'flutterfast-92c25',
    storageBucket: 'flutterfast-92c25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC8BRoGWWWnCm7AQoy4vEZyZjgYL_nkgQ',
    appId: '1:421526355060:ios:bbe26574f5be399cd5e521',
    messagingSenderId: '421526355060',
    projectId: 'flutterfast-92c25',
    storageBucket: 'flutterfast-92c25.appspot.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC8BRoGWWWnCm7AQoy4vEZyZjgYL_nkgQ',
    appId: '1:421526355060:ios:bbe26574f5be399cd5e521',
    messagingSenderId: '421526355060',
    projectId: 'flutterfast-92c25',
    storageBucket: 'flutterfast-92c25.appspot.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl2tfbtvpB_H9_W8lJqkQR6gdTPck1tk4',
    appId: '1:421526355060:web:77892592d1e53de5d5e521',
    messagingSenderId: '421526355060',
    projectId: 'flutterfast-92c25',
    authDomain: 'flutterfast-92c25.firebaseapp.com',
    storageBucket: 'flutterfast-92c25.appspot.com',
    measurementId: 'G-65GM1L8MFK',
  );

  final storage =
      FirebaseStorage.instanceFor(bucket: "gs://flutterfast-92c25.appspot.com");
}
